export enum GameErrors {
  PLAYER_HAVE_NO_START_GAME_ACCESS_RIGHTS = 'PLAYER_HAVE_NO_START_GAME_ACCESS_RIGHTS',
  NOT_ENOUGH_USERS_TO_START_GAME = 'NOT_ENOUGH_USERS_TO_START_GAME',
  GAME_IS_NOT_FOUND = 'GAME_IS_NOT_FOUND',
  FIRST_ROUND_ALREADY_CREATED = 'FIRST_ROUND_ALREADY_CREATED',
}
