export enum GameErrors {
  PLAYER_HAVE_NO_START_GAME_ACCESS_RIGHTS = 'PLAYER_HAVE_NO_START_GAME_ACCESS_RIGHTS',
  NOT_ENOUGH_USERS_TO_START_GAME = 'NOT_ENOUGH_USERS_TO_START_GAME',
  GAME_IS_NOT_FOUND = 'GAME_IS_NOT_FOUND',
  USER_IS_NOT_FOUND = 'USER_IS_NOT_FOUND',
}

export enum RoundErrors {
  ROUND_IS_NOT_FOUND = 'ROUND_IS_NOT_FOUND',
  PLAYER_HAVE_NO_FINISH_ROUND_ACCESS_RIGHTS = 'PLAYER_HAVE_NO_FINISH_ROUND_ACCESS_RIGHTS',
  FIRST_ROUND_ALREADY_CREATED = 'FIRST_ROUND_ALREADY_CREATED',
  CURRECT_ROUND_HAVE_NO_ACTIVE_ROLE = 'CURRECT_ROUND_HAVE_NO_ACTIVE_ROLE',
}
